on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform.yml'

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: "default"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS Access Key
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Access Key
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~1.0.0
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Post Terraform Plan as PR Comment
        if: github.event.pull_request.draft == false
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            ### Terraform Plan:
            ```
            ${{ steps.plan.outputs.stdout }}
            ```

      - name: Wait for PR Approval
        if: github.event.pull_request.draft == false
        uses: hmarr/auto-merge-action@v2
        with:
          merge-method: squash

      - name: Terraform Apply (On approval)
        if: github.event.pull_request.merged == true
        run: terraform apply -auto-approve tfplan

      - name: Rebase and Merge PR
        if: github.event.pull_request.merged == true
        run: |
          git fetch origin main
          git rebase origin/main
          git push origin HEAD:main
