name: Terraform Plan on PR
on:
  pull_request:
    branches:
      - main

jobs:
  parse-atlantis:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.parse.outputs.projects }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Parse Atlantis Config
        id: parse
        run: |
          projects=$(yq -o json '.projects[] | {dir, workspace}' atlantis.yaml | jq -c -s '.')
          echo "projects=$projects" >> $GITHUB_OUTPUT

  terraform-plan:
    needs: parse-atlantis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.parse-atlantis.outputs.projects) }}
    env:
      TF_WORKSPACE: ${{ matrix.project.workspace || 'default' }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ${{ matrix.project.dir }}
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: ${{ matrix.project.dir }}
        shell: bash
        run: |
          echo 'plan<<EOF' >> $GITHUB_OUTPUT
          terraform plan -no-color -out=tfplan >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.project.workspace || 'default' }}-plan"
          path: ${{ matrix.project.dir }}/tfplan

      - name: Comment Plan
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.HUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Terraform Plan for `${{ matrix.project.workspace || 'default' }}`:

            ```
            ${{ steps.plan.outputs.plan }}
            ```

            Plan saved to GitHub artifacts.
