name: Terraform Apply
on:
  pull_request_review:
    types: [submitted]

jobs:
  check-conditions:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    outputs:
      proceed: ${{ steps.check.outputs.proceed }}
    steps:
      - name: Check PR Status
        id: check
        run: |
          # Get PR details using GitHub API
          PR_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}")
          
          # Check if PR has conflicts
          MERGEABLE=$(echo "$PR_INFO" | jq -r '.mergeable')
          
          if [ "$MERGEABLE" = "true" ]; then
            echo "proceed=true" >> $GITHUB_OUTPUT
            echo "PR is approved and has no conflicts"
          else
            echo "proceed=false" >> $GITHUB_OUTPUT
            echo "PR has conflicts or is not mergeable"
            exit 1
          fi

  list-artifacts:
    needs: check-conditions
    if: needs.check-conditions.outputs.proceed == 'true'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Get Artifacts
        uses: actions/github-script@v6
        id: get-artifacts
        with:
          script: |
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const planArtifacts = artifacts.data.artifacts
              .filter(a => a.name.endsWith('-plan'))
              .map(a => {
                // Split name format: workspace-parentdir-dir-plan
                const parts = a.name.split('-');
                const workspace = parts[0];
                // Join all middle parts as the directory path
                const dir = parts.slice(1, -1).join('/');
                return { 
                  workspace: workspace,
                  dir: dir,
                  artifact_name: a.name
                };
              });
            return planArtifacts;

      - name: Set Matrix
        id: set-matrix
        run: |
          ARTIFACTS='${{ steps.get-artifacts.outputs.result }}'
          echo "matrix={\"include\":$ARTIFACTS}" >> $GITHUB_OUTPUT

  terraform-apply:
    needs: [check-conditions, list-artifacts]
    if: needs.check-conditions.outputs.proceed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.list-artifacts.outputs.matrix) }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Download Plan File
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.dir }}

      - name: Terraform Init
        working-directory: ${{ matrix.dir }}
        run: terraform init

      - name: Select Workspace
        if: ${{ matrix.workspace != 'default' }}
        working-directory: ${{ matrix.dir }}
        run: |
          terraform workspace select -or-create ${{ matrix.workspace }}

      - name: Terraform Apply
        id: apply
        working-directory: ${{ matrix.dir }}
        shell: bash
        run: |
          echo 'apply<<EOF' >> $GITHUB_OUTPUT
          terraform apply -no-color -auto-approve tfplan 2>&1 >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Comment Apply
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.HUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Terraform Apply for `Directory: ${{ matrix.dir }}` and `Workspace: ${{ matrix.workspace }}`:

            ```
            ${{ steps.apply.outputs.apply }}
            ```

            Apply completed.
