name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  TF_VERSION: "1.5.7" # Replace with your Terraform version
  TF_WORKING_DIR: "./" # Directory containing Terraform code

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform init

    - name: Terraform Plan
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform plan -out=tfplan

    - name: Comment Plan on PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: terraform-plan
        message: |
          ```terraform
          $(terraform show -json tfplan | jq '.')
          ```

    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch'
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform apply -auto-approve tfplan
